debug: true
#eureka服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  # DataSource Config
  datasource:
    url: jdbc:oracle:thin:@//10.2.12.14:1521/GGRDAT
    username: ora8gree
    password: greeora8321
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    # 最大连接数
    maxActive: 10


